### ISSUE TITLE
Requirements for a cross-wallet "Account Map" with xpubs

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Airgapped-Wallet-Community#6]
We have been working on an "Account Map" with xpubs, wallet descriptors, and other metadata for fully restoring a multisig account.

Though these can and should be able to be saved to disk, we imagine these as being printed on a QR code to accompany each seed that is backed up for that account — the scenario being you only need one of these papers to survive a fire or other tragedy and the quorum of seeds, and that the compromise of which only hurts your privacy, not your access to funds. Also, if a single seed is used with multiple multisig accounts, you only need to add this paper to your storage location, not re-archive the seed.

@peter-conalgo has shared a similar fomatted document in JSON in the most recent firmware of @ColdCard https://github.com/Coldcard/firmware/tree/master/docs/generic-wallet-export.md

My only reservation with this is that like some of the earlier proposals in this repo, using JSON may make it too large to print on a single QR code.

-- Christopher Allen

**Comment by ChristopherA** [comment]
@Fonta1n3 — can you share here an example of our latest Account Map prototype for Fully Node 2?

-- Christopher Allen

**Comment by Fonta1n3** [comment]
![image](https://user-images.githubusercontent.com/30832395/80771244-5e772800-8b85-11ea-96b2-2070e512b4b9.jpeg)

and the text:

```
{"birthdate":1587962035,"blockheight":1,"descriptor":"wsh(sortedmulti(2,[82be8e74\/48'\/1'\/0'\/2']tpubDEYij9WndcWU4ApaSz68RitBMrZRTfShsXn4qw1izEaFScR5dnP4dz1CzgmfT5iTrNeZJhMXieg2BzhCFNxrWtvaTerBio3VbFoSDixs4yR\/0\/*,[5222e39c\/48'\/1'\/0'\/2']tpubDEQznV4Xs6BP1A1HXzogRsUiFxDsyaqLzphZmjmwrrERz9aHszb2juQzYBx9xuXymba5kkQvR76m218JiXM1DsLcgPryGCDs5P1geHoxVrx\/0\/*,[81202613\/48'\/1'\/0'\/2']tpubDEcrpYzpqTJyhy5bzsojvL8VMrcFf4DVU7q43fuq6JhhNyxCqLzhppiUsMHAXUJv4XTnmAiezNAzdfTdg2FFefbzNh8YzN6Wv2zEYwcCC22\/0\/*))#czsstq8d","label":"2 of 3"}
```

**Comment by Fonta1n3** [comment]
For the privacy conscious an improvement could be a 2/4 or 3/5 where you save less then n xpubs with each seed, ensuring the seed also makes it less than n.

For example 2 alternate xpubs with each seed so that even if an attacker found one seed with a partial account map you would not lose privacy. 

Doesn’t work with 2/3 unfortunately as there would either be enough keys to recreate the wallet with each seed or not enough to recover if you only had m backups available.

Thanks to BIP67 the order of the xpubs doesn’t matter making this method simpler.

**Comment by aaronisme** [comment]
quick question here, does the birthdate, and blockheight are really needed to account ?

**Comment by Fonta1n3** [comment]
> quick question here, the birthdate, and blockheight are really needed to account ? 

No, it’s just convenient for restoring by automatically scanning the blockchain from a specific date.

**Comment by stepansnigirev** [comment]
@Fonta1n3 in this QR code I see that you only have receiving descriptor. What about the change one? Should the wallet derive change descriptor automatically somehow? If so, what happens when descriptor is defined with the non-hardened path not xpub/0/* but xpub/* or xpub/28/* ?

**Comment by Fonta1n3** [comment]
> @Fonta1n3 
> 
> In this QR code I see that you only have receiving descriptor. What about the change one? Should the wallet derive change descriptor automatically somehow? If so, what happens when descriptor is defined with the non-hardened path not `xpub/0/*` but `xpub/*` or `xpub/28/*` ?

The wallet should automatically derive the change descriptor. We have just been adhering to BIP44/49/84/48 so that it is clear. Not sure how to handle change if a user imports a non standard account.

With Specter we know how you guys handle it so it’s easy to adapt. However there is an infinite number of paths a user could potentially come up with. If it is custom i feel it should just be imported as is without being manipulated.

Do you have thoughts or guidelines on this?

**Comment by ChristopherA** [comment]
Though I prefer defining a new change type 2 for mixers, I could see people pushing all change to the custody of their mixer wallet with a different xpub.

— Christopher Allen

**Comment by ChristopherA** [comment]
I think a user label is important. Users may use one seed with multiple multisig accounts (especially given effort to put in titanium or steel). The will need to distinguish them.

— Christopher Allen
